elifesciences/profiles

- profiles/factory.py
- profiles/utilities.py
Not sure how PyCharm is running pytest differently, but it was showing some non HTTPExceptions not being handled (but still as  passes; `project_tests.sh` just showed passes).
> Fix non-HTTPException error handling

- profiles/api/oauth2.py
- test/test_oauth2.py
Clients should use the eLife ID rather than ORCID (though I've left in the original details).
Related: other OAuth2 implementers seem to require you to make a second request to find out such details, ORCID don't (and include the `orcid` property).
> Include ID in token response

- profiles/config.py
For forward compatibility, allow the formula to provide more configuration that needed (e.g. a `logging` key). This configuration is ignored.
> Allow additional, unused configuration

- pytest.ini
- requirements.txt
- test/test_oauth2.py
Switches `responses` to `requests-mock` as it allows us match on the request body, headers etc.
Also adds `pytest-socket` to block _all_ HTTP requests that haven't been mocked, rather than just cases where the mocker is enabled.
> Use requests-mock rather than responses

- migrations/versions/b619f44789e4_.py
- profiles/api/oauth2.py
- profiles/models.py
- test/test_oauth2.py
I assumed that no `name` would be provided if it were private (and so would fail), turns out that it's an empty string, which we've now persisted.
~Instead of hard-failing, this persists a clear fallback value.~
> Handle private names

- profiles/api/oauth2.py
- test/test_oauth2.py
For bugs like ELPP-3238, we probably should let users still authenticate rather than deny access. It means their profile will remain empty/incomplete.
> Gracefully fail on problems reading ORCID data

- migrations/versions/6e06221b94fa_.py
- profiles/commands.py
- profiles/models.py
- test/commands/test_update_profile_from_orcid_record.py
- test/models/test_affiliation.py
- test/models/test_date.py
- test/models/test_profile.py
- test/serializer/test_normalize.py
- test/test_api.py
Stores dates in separate parts, as we might be missing the month and day.
Would have like to have used the [EDTF library](https://github.com/ixc/python-edtf), but doesn't support Python 3 (and is untested etc).
> ELPP-3238 Handle partial ORCID dates

- Jenkinsfile.prod
This isn't generally a problem because only one build is performed at a time, but better to be consistent in all environments.
> Missing lock on profiles--prod deploy

- profiles/commands.py
- requirements.txt
- test/commands/test_update_profile_from_orcid_record.py
Seems unclear whether the ORCID responses should omit values or leave them as `null`, but they do the latter. JMESPath is probably a better way to traverse the uncertain structure (this doesn't do it _everywhere_).
> Use JMESPath to pick data out of the ORCID API response

- profiles/orcid.py
- test/test_orcid.py
Should now match https://members.orcid.org/api/tutorial/webhooks.
> Remove API version from webhook URI

- migrations/versions/d4f16fce7228_.py
- profiles/commands.py
- profiles/models.py
- test/commands/test_update_profile_from_orcid_record.py
- test/models/test_affiliation.py
While looking through the logs I saw that there's errors when missing an affiliation start date (@NickDuf's profile). Looking at the XSD for the API, it's possible for it to be missing. However, through the ORCID UI it's a required field, so this might be for legacy data.
This should handle it correctly.
> Handle missing affiliation start dates

- profiles/events.py
- profiles/utilities.py
- test/conftest.py
- test/events/test_maintain_orcid_webhook.py
- test/events/test_send_update_events.py
- test/utilities/test_catch_exceptions.py
Bad things seem to happen if an event handler raises any exception, it gets disconnected and the database transaction doesn't complete, requiring a restart.
> Catch any exception raised by an event handler

- .pylintrc
- project_tests.sh
This replaces the calls to `flake8` and `pylint` with `proofreader`. As this project currently has its own overrides the default configurations will be overridden. 
This means functionally nothing has changed but it brings the project closer in line with how other current and future Python-based projects are to be structured, at least in terms of linting and pre-test checks.
> Add proofreader

- .coveragerc
- README.md
- project_tests.sh
Added test coverage report generation and integration with [coveralls](https://coveralls.io/github/elifesciences/profiles).
I have disabled auto PR comments (so no spamming) and opted to not have this be an active check on PRs like we do in our libraries. This can be changed if need be in the repo settings and the failure percentage for a decrease can be configured in coveralls.
> Add test coverage

- profiles/cli.py
- profiles/factory.py
- test/cli/test_create_profile_command.py
- test/conftest.py
Primary use is for the ingestion of existing `{name: email}` pairs from other services.
> Add create profile cli command

- profiles/cli.py
This can be reverted after if we do not want to persist this functionality.
> Update name value via cli command if existing profile found

- profiles/cli.py
This is no longer needed and if required in the future can be implemented through a separate command so that `create-profile` does just what its name states.
> Removed ability to modify existing profile name through cli command

- profiles/api/errors.py
Don't know if this'll stop 400 responses from appearing in New Relic, but we seem to be logging them as `ERROR` level.
> Stop non-5xx responses being logged as errors

- Jenkinsfile.prod
We already have the `approved` tag updated, along with all the commit-based tags
> Push images with latest tag

- Jenkinsfile
We could always use this with an environment variable COMPOSE_FILE global to the server, but that would be *too* magic.
> Ci should build images using ci configuration

- smoke_tests.sh
It's a route that accesses the database, proving that the connection works
> Add /profiles to smoke tests

- config/uwsgi.ini
This is required by the New Relic agent. The agent is not running locally, but for consistency it's safer to use the same configuration everywhere
> Enable threads

- Jenkinsfile
- profiles/cli.py
- profiles/config.py
- profiles/factory.py
- smoke_tests_wsgi.sh
Started out to make them configurable, but it was more foolproof to just read the configuration to keep smoke tests easy to run from any user or automated process.
> Automatically read web and db hosts in smoke tests

- README.md
- clients.yaml.dist
- config/clients.yaml
- docker-compose.ci.yml
- manage.py
- profiles/api/oauth2.py
- profiles/clients.py
- profiles/exceptions.py
- test/clients/test_client.py
- test/clients/test_clients.py
- test/conftest.py
Will make both `elifesciences.org` and `elifejournal.org` (for Fastly testing) supported at the same time.
Formula to be updated prior to merge, upon approval.
> ELPP-3393 Introduce redirect_uris in place of redirect_uri

- Jenkinsfile
These are throwaway instances so the image may have never been pulled on one.
> Push from containers new nodes

- profiles/commands.py
- test/test_webhook.py
Relates to https://github.com/elifesciences/issues/issues/4633
Fix for db getting into broken transaction state.
Seems to be an issue with either Flask-SQLAlchemy or SQLAlchemy. Either way, no exception is raised by either framework. The problem becomes apparent when trying to access the database after the database is in a broken state.
I have tried updating all dependencies to the latest version but the problem still persists.
My solution is to add a check to see if an email in an incoming ORCID record tries to update a profile with an email associated with another profile. If the email already exists the error is logged and the email is removed from the list of emails to process/update.
> fix db getting into broken state

- Pipfile.lock
PR was to update Jinja2 to version 2.10.1 for https://github.com/elifesciences/issues/issues/4874 but appears to be difficult with pipenv as it will update other packages also. However, tests run without issue for dev environment.
> update outdated packages

- Pipfile
- Pipfile.lock
- test/test_404.py
> fix for CVE-2019-1010083, bumps flask to >1.0.0

- Pipfile
- Pipfile.lock
- config/uwsgi.ini
- project_tests.sh
also fixes 'elife-api-validator' Pipfile entry
> proofreader-python, removed as a dependency, removed from tests

- profiles/api/webhook.py
Fix for this error:
```json
{
"name": "profiles.api.errors",
"message": "'NoneType' object has no attribute 'status_code'",
"asctime": "2023-04-29 13:15:34,946",
"levelname": "ERROR",
"exc_info": {
"message": "'NoneType' object has no attribute 'status_code'",
"class": "AttributeError",
"trace": [
"  File \"/srv/profiles/venv/lib/python3.8/site-packages/flask/app.py\", line 1823, in full_dispatch_request\n    rv = self.dispatch_request()\n",
"  File \"/srv/profiles/venv/lib/python3.8/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
"  File \"/srv/profiles/venv/lib/python3.8/site-packages/newrelic/hooks/framework_flask.py\", line 82, in _nr_wrapper_handler_\n    return wrapped(*args, **kwargs)\n", …
```
> bugfix, RequestException.response may be None in some cases.

- Jenkinsfile.prune-blocked
- profiles/cli.py
prune-blocked, bumps timeout to 16hrs
prune-blocked, adds some useful output to know how far we've gotten. prune-blocked, disabled webhook remove, it seems to do this itself on COMMIT prune-blocked, adds explicit COMMIT after finding and deleting a profile.
pretty sure this wasn't happening.
prune-blocked, disabled throttle, job isn't completing inside a reasonable timeout.
> prune-blocked, more changes
